"""add login index.

Revision ID: 1a7d06dd652b
Revises: f8e1a8684247
Create Date: 2025-09-27 06:06:10.263405

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "1a7d06dd652b"
down_revision = "f8e1a8684247"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_login"), "users", type_="unique")
    op.create_index(op.f("ix_users_login"), "users", ["login"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_login"), table_name="users")
    op.create_unique_constraint(op.f("uq_users_login"), "users", ["login"], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
