name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v3
      - run: uv python install 3.13
      - run: |
          uv sync --all-extras --frozen --no-install-project
          uv run ruff format . --check
          uv run ruff check . --no-fix

  pytest:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v3
      - run: uv python install 3.13
      - run: |
          uv sync --all-extras --frozen --no-install-project
          uv run alembic upgrade head
          uv run pytest . --cov=. --cov-report html
        env:
          SERVICE_ENVIRONMENT: ci
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1
          DB_DSN: postgresql+asyncpg://postgres:password@127.0.0.1/postgres
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          path: ./htmlcov
          name: coverage-report
